[package]
name = "raytracing_rust"
version = "0.1.0"
authors = ["Hao Luo <howlowck@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33.1"
indicatif = "0.15.0"
